[project]
name = "if4020-cipher-backend"
version = "0.1"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "numpy",
    "python-multipart",
    "jinja2"
]
requires-python = ">= 3.8"

[tool.setuptools]
py-modules = []
